/**
 * RFC 7807 Problem Details for HTTP APIs (application/problem+json).
 * Standardized error response structure conforming to RFC 7807.
 */
export interface ProblemDetails {
  /**
   * A URI reference [RFC3986] that identifies the problem type.
   * Defaults to "about:blank" when no specific URI is defined.
   */
  readonly type: string;

  /**
   * A short, human-readable summary of the problem type.
   * Should not change from occurrence to occurrence of the problem,
   * except for purposes of localization.
   */
  readonly title: string;

  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  readonly status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  readonly detail: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem (safe request path).
   */
  readonly instance: string;

  /**
   * Distributed request correlation identifier.
   */
  readonly correlation_id: string;

  /**
   * Optional field-level validation errors or metadata (safe only).
   */
  readonly errors?: ReadonlyArray<{ readonly field?: string; readonly message: string }>;
}
